player_1_name: "Player-1"
player_2_name: "Player-2"
train_llm_name: "meta-llama/Llama-3.2-3B-Instruct"
opponent_llm_name: "meta-llama/Llama-3.2-3B-Instruct"
trained_player: 2 # 1 or 2 or "both"

train:
  lr: 1e-5
  epochs: 300
  batches_per_epoch: 1
  group_size: 8
  minibatch_size: 1
  max_interactions: 5
  kl_coef: 0.1
  ppo_eps: 0.2
  grpo_std_eps: 1e-8

wandb:
  project: "rock-paper-scissors"
  name: "memory&time-tracking"

prompts:
  folder: "prompts/RPS/"
  initial: "initial.txt"
  other_moved: "other_moved.txt"

lora:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.0


###### Not modifiable configuration ######

tracked_metrics: [
  "total_loss",
  "kl",
  "win_rate",
  "draw_rate",
  "loss_rate",
  "num_samples",
  "memory_usage_generation (GB)",
  "memory_usage_minibatch (GB)",
  "time_generation (s)",
  "time_minibatch (s)",
  "time_total_minibatches (s)"
]

# metrics to be divided by number of samples
normalized_metrics: [
  "total_loss",
  "kl",
  "win_rate",
  "draw_rate",
  "loss_rate"
]