player_1_name: "Player-1"
player_2_name: "Player-2"
train_llm_name: "meta-llama/Llama-3.2-3B-Instruct"
opponent_llm_name: "meta-llama/Llama-3.2-3B-Instruct"
trained_player: 2 # 1 or 2 or "both"

train:
  lr: 1e-5
  epochs: 100
  batches_per_epoch: 1
  group_size: 8
  minibatch_size: 1
  max_interactions: 5
  kl_coef: 0.1
  ppo_eps: 0.2
  grpo_std_eps: 1e-8

wandb:
  project: "rock-paper-scissors"
  name: "initial-code"

prompts:
  folder: "prompts/RPS/"
  initial: "initial.txt"
  other_moved: "other_moved.txt"

lora:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.0